# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY PipelineApp.jar /app/PipelineApp.jar
COPY IOT-temp-Test.csv /app/
COPY metadata.json /app/
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Run the jar file
CMD ["java","-jar", "PipelineApp.jar"]
